# Support the author of this open-source project by using the links below
# 
# This project is developed and maintained by Julian Bilcke with the help of amazing contributors
#
# I develop open-source apps both for work (I usually work alone),
# and for pleasure during my free time!
#
# I spend a lot of time working on my projects during the evening and weekend,
# buy you know, I have absolutely zero regrets because #YOLO
#
# If you like my work, do not hesitate to give a tip! I appreciate it ☕🫶

# GitHub(s):

# pro account (newer best projects): https://github.com/jbilcke-hf
# private account (older projects): https://github.com/jbilcke

# Hugging Face
# pro account: https://huggingface.co/jbilcke-hf

# Buy Me A Coffee
# https://buymeacoffee.com/flngr

github: jbilcke-hf
buy_me_a_coffee: flngr
